import { useState, useRef, useEffect, useCallback } from "react";

const MONO = "'IBM Plex Mono', 'Courier New', monospace";
const SANS = "'DM Sans', 'Helvetica Neue', sans-serif";

/* ─── Mock API ────────────────────────────────────────────────
   Simulates a delayed backend that returns text and/or files.
   Replace mockApiCall with a real fetch to your endpoint.
   API contract:  POST { message: string, urls: string[] }
   Response:      { text: string, files?: [{ name, url, size }] }
   ──────────────────────────────────────────────────────────── */
async function mockApiCall({ message, urls }) {
  const delay = (ms) => new Promise((r) => setTimeout(r, ms));

  // Simulate LLM chain latency (2-5s)
  await delay(2000 + Math.random() * 3000);

  const lowerMsg = message.toLowerCase();

  // Simulate a file response for certain keywords
  if (lowerMsg.includes("report") || lowerMsg.includes("export") || lowerMsg.includes("file") || lowerMsg.includes("download")) {
    const fakeContent = `# Analysis Report\n\nGenerated from ${urls.length} URL(s).\n\nQuery: ${message}\n\nURLs analyzed:\n${urls.map((u, i) => `${i + 1}. ${u}`).join("\n")}\n\n## Findings\nThis is a mock report generated by the simulated backend.\nReplace mockApiCall() with your real API to get actual results.`;
    const blob = new Blob([fakeContent], { type: "text/markdown" });
    return {
      text: `Report generated from ${urls.length} source(s). Download attached.`,
      files: [
        {
          name: "analysis-report.md",
          url: URL.createObjectURL(blob),
          size: blob.size,
          type: "text/markdown",
        },
      ],
    };
  }

  // Default: return text only
  return {
    text: `Processed your request across ${urls.length} URL(s):\n\n${urls.map((u) => `• ${u}`).join("\n")}\n\nYour message: "${message}"\n\nThis is a simulated response. The real backend would run your prompt through the LLM pipeline here. Replace mockApiCall() in the source to connect to your actual API.`,
  };
}

async function realApiCall({ message, urls }) {
  const res = await fetch("http://localhost:8000/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ message, urls }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return { text: data.llm_reply, files: [] };
}

async function generateChangeRequest({ description, urls }) {
  const res = await fetch("http://localhost:8000/change-request", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ description, urls }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return data;
}

/* ─── Components ──────────────────────────────────────────── */

function UrlTag({ url, onRemove }) {
  return (
    <div style={{
      display: "inline-flex", alignItems: "center", gap: 6,
      background: "var(--tag-bg)", border: "1px solid var(--border)",
      borderRadius: 4, padding: "3px 6px 3px 8px",
      fontFamily: MONO, fontSize: 11, color: "var(--text)",
      maxWidth: "100%", wordBreak: "break-all", lineHeight: 1.4,
    }}>
      <span style={{ opacity: 0.35, flexShrink: 0 }}>↗</span>
      <span style={{ flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{url}</span>
      <button onClick={onRemove} style={{
        background: "none", border: "none", color: "var(--text-muted)",
        cursor: "pointer", padding: "0 2px", fontSize: 13, lineHeight: 1,
        fontFamily: MONO, flexShrink: 0,
      }} title="Remove">×</button>
    </div>
  );
}

function FileAttachment({ file }) {
  return (
    <a
      href={file.url}
      download={file.name}
      style={{
        display: "flex", alignItems: "center", gap: 10,
        padding: "8px 12px", background: "var(--accent-dim)",
        border: "1px solid rgba(16,185,129,0.2)", borderRadius: 6,
        textDecoration: "none", color: "var(--text)",
        transition: "border-color 0.2s", marginTop: 8,
      }}
      onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--accent)")}
      onMouseLeave={(e) => (e.currentTarget.style.borderColor = "rgba(16,185,129,0.2)")}
    >
      <div style={{
        width: 28, height: 28, borderRadius: 4,
        background: "rgba(16,185,129,0.15)", display: "flex",
        alignItems: "center", justifyContent: "center", fontSize: 13, flexShrink: 0,
      }}>📄</div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontFamily: MONO, fontSize: 12, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
          {file.name}
        </div>
        {file.size && (
          <div style={{ fontSize: 10, color: "var(--text-muted)", marginTop: 1 }}>
            {file.size < 1024 ? `${file.size} B` : `${(file.size / 1024).toFixed(1)} KB`}
          </div>
        )}
      </div>
      <span style={{ fontSize: 11, color: "var(--accent)", fontFamily: MONO, flexShrink: 0 }}>↓ download</span>
    </a>
  );
}

function ChatBubble({ msg }) {
  const isUser = msg.role === "user";
  return (
    <div style={{
      display: "flex", justifyContent: isUser ? "flex-end" : "flex-start",
      animation: "slideUp 0.25s ease",
    }}>
      <div style={{
        maxWidth: "82%",
        padding: "10px 14px",
        borderRadius: isUser ? "14px 14px 4px 14px" : "14px 14px 14px 4px",
        background: isUser ? "var(--user-bubble)" : "var(--surface)",
        border: isUser ? "none" : "1px solid var(--border)",
        fontFamily: SANS, fontSize: 14, lineHeight: 1.6,
        color: "var(--text)", whiteSpace: "pre-wrap", wordBreak: "break-word",
      }}>
        {msg.text}
        {msg.files && msg.files.length > 0 && (
          <div style={{ marginTop: 4 }}>
            {msg.files.map((f, i) => <FileAttachment key={i} file={f} />)}
          </div>
        )}
        <div style={{
          fontFamily: MONO, fontSize: 10, color: "var(--text-muted)",
          marginTop: 6, opacity: 0.6,
          textAlign: isUser ? "right" : "left",
        }}>
          {msg.time}
        </div>
      </div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div style={{ display: "flex", justifyContent: "flex-start", animation: "slideUp 0.2s ease" }}>
      <div style={{
        padding: "12px 18px", borderRadius: "14px 14px 14px 4px",
        background: "var(--surface)", border: "1px solid var(--border)",
        display: "flex", gap: 5, alignItems: "center",
      }}>
        {[0, 1, 2].map((i) => (
          <span key={i} style={{
            width: 6, height: 6, borderRadius: "50%",
            background: "var(--text-muted)",
            animation: `dotBounce 1.2s ease-in-out ${i * 0.15}s infinite`,
          }} />
        ))}
      </div>
    </div>
  );
}

/* ─── Main App ────────────────────────────────────────────── */

export default function App() {
  const [urls, setUrls] = useState([]);
  const [urlInput, setUrlInput] = useState("");
  const [chatInput, setChatInput] = useState("");
  const [description, setDescription] = useState("");
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const chatEndRef = useRef(null);
  const inputRef = useRef(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(scrollToBottom, [messages, loading]);

  const addUrl = useCallback(() => {
    const raw = urlInput.trim();
    if (!raw) return;
    // Split on commas with any surrounding whitespace
    const parts = raw.split(/\s*,\s*/).map((s) => s.trim()).filter(Boolean);
    const toAdd = [];
    for (const part of parts) {
      try {
        new URL(part.startsWith("http") ? part : `https://${part}`);
      } catch { continue; }
      const normalized = part.startsWith("http") ? part : `https://${part}`;
      if (!urls.includes(normalized) && !toAdd.includes(normalized)) {
        toAdd.push(normalized);
      }
    }
    if (toAdd.length > 0) setUrls((p) => [...p, ...toAdd]);
    setUrlInput("");
  }, [urlInput, urls]);

  const now = () => new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  const handleSend = async () => {
    const text = chatInput.trim();
    if (!text || loading) return;

    const userMsg = { role: "user", text, time: now() };
    setMessages((p) => [...p, userMsg]);
    setChatInput("");
    setLoading(true);

    try {
      // ── Replace mockApiCall with realApiCall (or fetch) here ──
      const result = await realApiCall({ message: text, urls });

      const botMsg = {
        role: "assistant",
        text: result.text || "",
        files: result.files || [],
        time: now(),
      };
      setMessages((p) => [...p, botMsg]);
    } catch (err) {
      setMessages((p) => [
        ...p,
        { role: "assistant", text: `Error: ${err.message}`, time: now() },
      ]);
    } finally {
      setLoading(false);
      inputRef.current?.focus();
    }
  };

  const handleGenerateCR = async () => {
    if (urls.length === 0 || loading) return;
    setLoading(true);

    const userMsg = {
      role: "user",
      text: `Generate Change Request for ${urls.length} URL(s)${description.trim() ? `\n\nDescription: ${description}` : ""}`,
      time: now(),
    };
    setMessages((p) => [...p, userMsg]);

    try {
      const result = await generateChangeRequest({ description, urls });

      setMessages((p) => [
        ...p,
        { role: "assistant", text: `**Summary:**\n${result.summary}`, time: now() },
        { role: "assistant", text: result.change_request, time: now() },
      ]);
    } catch (err) {
      setMessages((p) => [
        ...p,
        { role: "assistant", text: `Error: ${err.message}`, time: now() },
      ]);
    } finally {
      setLoading(false);
      inputRef.current?.focus();
    }
  };

  const handleReset = () => {
    setMessages([]);
    setUrls([]);
    setUrlInput("");
    setChatInput("");
    setDescription("");
    setLoading(false);
  };

  return (
    <div style={{
      "--bg": "#0c0e10",
      "--surface": "#15181c",
      "--surface-raised": "#1c2026",
      "--border": "#262b33",
      "--border-focus": "#3d4450",
      "--text": "#dfe1e5",
      "--text-muted": "#5c6370",
      "--accent": "#10b981",
      "--accent-dim": "rgba(16,185,129,0.08)",
      "--tag-bg": "#181c21",
      "--user-bubble": "#1a3a2a",
      "--error": "#ef4444",
      height: "100vh", display: "flex", flexDirection: "column",
      background: "var(--bg)", color: "var(--text)", fontFamily: SANS,
      overflow: "hidden",
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700&family=IBM+Plex+Mono:wght@400;500&display=swap');
        @keyframes slideUp { from { opacity:0; transform:translateY(6px); } to { opacity:1; transform:translateY(0); } }
        @keyframes dotBounce {
          0%,60%,100% { transform:translateY(0); opacity:0.4; }
          30% { transform:translateY(-4px); opacity:1; }
        }
        ::selection { background:var(--accent); color:var(--bg); }
        textarea:focus, input:focus { outline:none; border-color:var(--border-focus)!important; }
        *{box-sizing:border-box;}
        ::-webkit-scrollbar { width:5px; }
        ::-webkit-scrollbar-track { background:transparent; }
        ::-webkit-scrollbar-thumb { background:var(--border); border-radius:4px; }
      `}</style>

      {/* ─── Top Bar ─── */}
      <div style={{
        padding: "14px 20px", borderBottom: "1px solid var(--border)",
        display: "flex", alignItems: "center", gap: 12, flexShrink: 0,
      }}>
        <div style={{
          width: 8, height: 8, borderRadius: "50%",
          background: urls.length > 0 ? "var(--accent)" : "var(--text-muted)",
          transition: "background 0.3s",
        }} />
        <div>
          <div style={{ fontFamily: SANS, fontSize: 15, fontWeight: 600 }}>URL Dispatcher</div>
          <div style={{ fontFamily: MONO, fontSize: 10, color: "var(--text-muted)", marginTop: 1 }}>
            {urls.length} source{urls.length !== 1 ? "s" : ""} loaded
          </div>
        </div>
      </div>

      {/* ─── URL Bar ─── */}
      <div style={{
        padding: "10px 20px", borderBottom: "1px solid var(--border)",
        flexShrink: 0, background: "var(--surface)",
      }}>
        <div style={{ display: "flex", gap: 8, marginBottom: urls.length > 0 ? 8 : 0 }}>
          <input
            type="text"
            placeholder="Add URLs (comma-separated)…"
            value={urlInput}
            onChange={(e) => setUrlInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addUrl(); } }}
            style={{
              flex: 1, padding: "7px 10px", background: "var(--bg)",
              border: "1px solid var(--border)", borderRadius: 5,
              color: "var(--text)", fontFamily: MONO, fontSize: 12,
            }}
          />
          <button onClick={addUrl} disabled={!urlInput.trim()} style={{
            padding: "7px 14px", background: "var(--surface-raised)",
            border: "1px solid var(--border)", borderRadius: 5,
            color: "var(--text)", fontFamily: MONO, fontSize: 11,
            cursor: !urlInput.trim() ? "default" : "pointer",
            opacity: !urlInput.trim() ? 0.35 : 1, transition: "opacity 0.15s",
            whiteSpace: "nowrap",
          }}>+ Add</button>
        </div>
        {urls.length > 0 && (
          <div style={{ display: "flex", flexWrap: "wrap", gap: 5, alignItems: "center" }}>
            {urls.map((url, i) => (
              <UrlTag key={i} url={url} onRemove={() => setUrls((p) => p.filter((_, j) => j !== i))} />
            ))}
            <button
              onClick={() => setUrls([])}
              style={{
                background: "none", border: "none",
                color: "var(--text-muted)", fontFamily: MONO, fontSize: 10,
                cursor: "pointer", padding: "3px 6px",
                textDecoration: "underline", textUnderlineOffset: 3,
                transition: "color 0.15s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "var(--error)")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text-muted)")}
            >
              clear all
            </button>
          </div>
        )}
      </div>

      {/* ─── Description & Generate CR ─── */}
      <div style={{
        padding: "10px 20px", borderBottom: "1px solid var(--border)",
        flexShrink: 0, background: "var(--surface)",
      }}>
        <textarea
          placeholder="Describe the change (context, motivation, constraints)…"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={2}
          style={{
            width: "100%", padding: "8px 10px", background: "var(--bg)",
            border: "1px solid var(--border)", borderRadius: 5,
            color: "var(--text)", fontFamily: SANS, fontSize: 13,
            resize: "vertical", lineHeight: 1.5, minHeight: 42, maxHeight: 160,
          }}
        />
        <button
          onClick={handleGenerateCR}
          disabled={urls.length === 0 || loading}
          style={{
            marginTop: 8, padding: "8px 18px",
            background: urls.length === 0 || loading ? "var(--surface-raised)" : "var(--accent)",
            border: "1px solid var(--border)", borderRadius: 6,
            color: urls.length === 0 || loading ? "var(--text-muted)" : "#0c0e10",
            fontFamily: MONO, fontSize: 12, fontWeight: 500,
            cursor: urls.length === 0 || loading ? "default" : "pointer",
            opacity: urls.length === 0 || loading ? 0.5 : 1,
            transition: "all 0.2s",
          }}
        >
          Generate Change Request
        </button>
      </div>

      {/* ─── Chat Area ─── */}
      <div style={{
        flex: 1, overflowY: "auto", padding: "20px 20px 8px",
        display: "flex", flexDirection: "column", gap: 12,
      }}>
        {messages.length === 0 && !loading && (
          <div style={{
            flex: 1, display: "flex", flexDirection: "column",
            alignItems: "center", justifyContent: "center", gap: 8, opacity: 0.35,
          }}>
            <div style={{ fontSize: 28 }}>↑</div>
            <div style={{ fontFamily: MONO, fontSize: 12, textAlign: "center", lineHeight: 1.6 }}>
              Add URLs above, then send a message
            </div>
          </div>
        )}
        {messages.map((msg, i) => <ChatBubble key={i} msg={msg} />)}
        {loading && <TypingIndicator />}
        <div ref={chatEndRef} />
      </div>

      {/* ─── Input Bar ─── */}
      <div style={{
        padding: "12px 20px 16px", borderTop: "1px solid var(--border)",
        flexShrink: 0, background: "var(--surface)",
      }}>
        <div style={{ display: "flex", gap: 8, alignItems: "flex-end" }}>
          {messages.length > 0 && !loading && (
            <button
              onClick={handleReset}
              title="Reset conversation"
              style={{
                height: 42, padding: "0 14px", borderRadius: 8, flexShrink: 0,
                background: "var(--surface-raised)",
                border: "1px solid var(--border)",
                color: "var(--text-muted)", fontFamily: MONO, fontSize: 11,
                cursor: "pointer", transition: "all 0.2s",
                animation: "slideUp 0.2s ease",
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = "var(--error)"; e.currentTarget.style.color = "var(--error)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = "var(--border)"; e.currentTarget.style.color = "var(--text-muted)"; }}
            >
              Reset
            </button>
          )}
          <textarea
            ref={inputRef}
            placeholder="Describe what to do with these URLs…"
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); }
            }}
            disabled={loading}
            rows={1}
            style={{
              flex: 1, padding: "10px 12px", background: "var(--bg)",
              border: "1px solid var(--border)", borderRadius: 8,
              color: "var(--text)", fontFamily: SANS, fontSize: 14,
              resize: "none", lineHeight: 1.5,
              minHeight: 42, maxHeight: 120,
            }}
            onInput={(e) => {
              e.target.style.height = "auto";
              e.target.style.height = Math.min(e.target.scrollHeight, 120) + "px";
            }}
          />
          <button
            onClick={handleSend}
            disabled={loading || !chatInput.trim()}
            style={{
              width: 42, height: 42, borderRadius: 8, flexShrink: 0,
              background: !chatInput.trim() ? "var(--surface-raised)" : "var(--accent)",
              border: "1px solid var(--border)",
              color: !chatInput.trim() ? "var(--text-muted)" : "#0c0e10",
              fontSize: 18, cursor: loading ? "wait" : "pointer",
              display: "flex", alignItems: "center", justifyContent: "center",
              transition: "all 0.2s",
            }}
          >
            ↑
          </button>
        </div>
      </div>
    </div>
  );
}